steps:
- name: 'gcr.io/cloud-builders/npm'  
  args: ['install', '--prefix', './functions/']
- name: 'gcr.io/cloud-builders/npm'  
  args: ['test', '--prefix', './functions/']
- name: 'gcr.io/cloud-builders/gcloud' 
  args: ['functions', 'deploy', 'helloWorld', '--source', './functions/', '--runtime', 'nodejs8', '--trigger-http']